<!doctype html>

<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>

  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><?php echo $web_name['option_value']; ?> | Privacy policy</title>

  <link rel="stylesheet" href="<?= SITE_URL ?>assets/web/css/style.css">

  <link rel="stylesheet" href="<?= SITE_URL ?>assets/web/css/bootstrap.min.css">

  <link rel="stylesheet" href="<?= SITE_URL ?>assets/web/css/bootstrap.css">

  <link rel="stylesheet" href="<?= SITE_URL ?>assets/web/css/aos.css">

  <script src="<?= SITE_URL ?>assets/web/js/aos.js"></script>

  <script src="<?= SITE_URL ?>assets/web/js/bootstrap.js"></script>

  <script src="<?= SITE_URL ?>assets/web/js/bootstrap.min.js"></script>

  <script src="<?= SITE_URL ?>assets/web/js/custom.js"></script>

  <link rel="stylesheet" href="../cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

</head>
<style>
  @media only screen and (min-width: 320px) and (max-width: 575px) {
    .privacy-sec {
      margin-top: 100px !important;
    }

    .snip1168 a {
      font-size: 11px !important;
    }
  }

  @media only screen and (min-width: 575px) and (max-width: 1100px) {
    .privacy-sec {
      margin-top: 150px !important;
    }
  }
</style>

<body>

  <header>

    <nav class="navbar navbar-expand-lg header navbar-default fixed-top" style="background: rgb(255 255 255 / 90%);" id="nav">

      <div class="container">
          <?php $logo = $web_logo['option_value']; ?>
        <a class="navbar-brand" href="<?= SITE_URL ?>"><img src="<?php echo $logo; ?>" alt="logo"></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">

          <span class="navbar-toggler-icon"><i class="fa fa-bars"></i></span>

        </button>

        <div class="" id="navbarTogglerDemo01">

          <ul class="navbar-nav snip1168 ml-auto mt-2 mt-lg-0">

            <li class="nav-item active">

              <a class="nav-link" href="<?= SITE_URL ?>">Back to Home</a>

            </li>

          </ul>

        </div>

      </div>

    </nav>

  </header>

  <section style="margin-top:10%" class="privacy-sec">

<div class="container">

  <h3>Privacy Policy</h3>

  <p>This Privacy Policy explains our practices regarding the collection, use, and disclosure of your information when you use our service. It also outlines your privacy rights and legal protections.</p>

  <p>We use your personal data to provide and improve the service, and by using it, you agree to the terms outlined in this Privacy Policy.</p>

  <h3>Interpretation and Definitions</h3>

  <h4>Interpretation</h4>

  <p>Capitalized terms in this Privacy Policy have specific meanings. These definitions apply regardless of whether the terms appear in singular or plural form.</p>

  <h4>Definitions</h4>

  <p>For the purpose of this Privacy Policy:</p>

  <ul>

    <li>

      <p><strong>Account</strong>: refers to a unique account created for accessing our service or parts of it.</p>

    </li>

    <li>

      <p><strong>Affiliate</strong>: refers to an entity that controls, is controlled by, or is under common control with us.</p>

    </li>

    <li>

      <p><strong>Application</strong>: refers to the software program named <?= SITE_NAME ?> Game, provided by the Company and downloaded on any electronic device.</p>

    </li>

    <li>

      <p><strong>Company</strong>: refers to <?= SITE_NAME ?> Game.</p>

    </li>

    <li>

      <p><strong>Country</strong>: refers to Rajasthan, India.</p>

    </li>

    <li>

      <p><strong>Device</strong>: refers to any device such as a computer, cellphone, or digital tablet that can access the service.</p>

    </li>

    <li>

      <p><strong>Personal Data</strong>: refers to any information that relates to an identified or identifiable individual.</p>

    </li>

    <li>

      <p><strong>Service</strong>: refers to the Application.</p>

    </li>

    <li>

      <p><strong>Service Provider</strong>: refers to any natural or legal person who processes data on our behalf. This includes third-party companies or individuals employed by us to facilitate the service, provide the service, perform services related to the service, or assist us in analyzing how the service is used.</p>

    </li>

    <li>

      <p><strong>Usage Data</strong>: refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself.</p>

    </li>

    <li>

      <p><strong>You</strong>: refers to the individual accessing or using the service, or the company or other legal entity on behalf of which the individual is accessing or using the service.</p>

    </li>

  </ul>

  <h3>Collecting and Using Your Personal Data</h3>

  <h4>Types of Data Collected</h4>

  <h3>Personal Data</h3>

  <p>While using our service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you. This information may include your email address, first name, last name, phone number, address, state, province, ZIP/postal code, city, and usage data.</p>

  <h3>Usage Data</h3>

  <p>Usage Data is collected automatically when using the service. It may include information such as your device's IP address, browser type, browser version, pages visited, time and date of visits, time spent on pages, unique device identifiers, and other diagnostic data. When accessing the service through a mobile device, additional information may be collected, including the type of mobile device, mobile device unique ID, mobile device's IP address, mobile operating system, type of mobile internet browser, unique device identifiers, and other diagnostic data. Information sent by your browser when visiting our service or accessing it through a mobile device may also be collected.</p>

  <h3>Information Collected while Using the Application</h3>

  <p>While using our application, we may collect information regarding your location with your prior permission. This information is used to provide and improve the service and may be stored on our servers or your device, based on your settings.</p>

  <h4>Use of Your Personal Data</h4>

  <p>We may use your personal data for various purposes, including providing and maintaining the service, managing your account, performing contracts, contacting you for updates or informative communications, providing news and offers, managing your requests, evaluating business transfers, conducting data analysis, and improving our service, products, and marketing efforts.</p>

  <p>We may share your personal information with service providers, business partners, affiliates, and other users, as well as in connection with business transactions and legal requirements.</p>

  <h3>Retention and Transfer of Your Personal Data</h3>

  <p>We retain your personal data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy. Your data may be transferred to and processed in other locations, including countries with different data protection laws than your own. We take reasonable steps to ensure the security and protection of your data during transfer and processing.</p>

  <h3>Disclosure of Your Personal Data</h3>

  <h4>Business Transactions</h4>

  <p>In the event of a merger, acquisition, or asset sale, your personal data may be transferred subject to a different Privacy Policy. We will provide notice before your personal data is transferred in such circumstances.</p>

  <h4>Law Enforcement</h4>

  <p>We may disclose your personal data if required to do so by law or in response to valid requests by public authorities.</p>

  <h3>Other Legal Requirements</h3>

  <p>We may disclose your personal data in good faith belief if it is necessary to comply with a legal obligation, protect our rights or property, prevent wrongdoing, ensure personal safety, or protect against legal liability.</p>

  <h4>Security of Your Personal Data</h4>

  <p>While we strive to protect your personal data using commercially acceptable means, no method of transmission or storage over the Internet is 100% secure. We cannot guarantee the absolute security of your data.</p>

  <h3>Children's Privacy</h3>

  <p>Our service is not intended for children under the age of 13, and we do not knowingly collect personally identifiable information from anyone under the age of 13. If you believe we have collected personal data from a child without parental consent, please contact us to have it removed.</p>

  <h3>Links to Other Websites</h3>

  <p>Our service may contain links to other websites that are not operated by us. We advise you to review the privacy policies of those third-party sites as we have no control over and assume no responsibility for their content or practices.</p>

  <h3>Changes to this Privacy Policy</h3>

  <p>We may update this Privacy Policy periodically, and we will notify you of any changes. You should review this Privacy Policy periodically for the latest information.</p>

  <h3>Contact Us</

If you have any questions about this Privacy Policy, please contact us:

</div>
  </section>

  <footer class="footer">

    <div class="container">

      <div class="footer-content">

        <p>Copyright 2021 <a href="<?= SITE_URL ?>"><?=$web_name['option_value']?></a> | All Rights Reserved | <a href="<?= SITE_URL ?>privacy_policy">Privacy Policy</a></p>
        <!--<p class="white"><a href="https://www.searchnplay.in/" target="_blank">Website Development Company : Search N Play</a></p>-->
      </div>

    </div>

  </footer>